[package]

name = "reforge"
version = "0.0.0"
authors = [
    "tedsta <tderego94@gmail.com>"
]

[features]

default = ["client"]

client = []

[[bin]]

name = "reforge_client"
path = "src/client.rs"

#[[bin]]

#name = "reforge_server"
#path = "src/server.rs"

[dependencies.pistoncore-sdl2_window]

git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.piston2d-opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.piston]

git = "https://github.com/pistondevelopers/piston"

[dependencies.bincode]

git = "https://github.com/tyoverby/bincode.git"

[dependencies.time]

git = "https://github.com/rust-lang/time"

[dependencies]

rustc-serialize = "0.2.7"
