[package]

name = "reforge"
version = "0.0.0"
authors = [
    "tedsta <tderego94@gmail.com>"
]

[[bin]]

name = "reforge_client"
path = "src/client.rs"
cfg = ["client"]

#[[bin]]

#name = "reforge_server"
#path = "src/server.rs"

[dependencies.sdl2_window]

git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.piston]

git = "https://github.com/pistondevelopers/piston"

[dependencies.bincode]

git = "https://github.com/tedsta/bincode"