[package]

name = "reforge"
version = "0.0.0"
authors = [
    "tedsta <tderego94@gmail.com>"
]

[features]

default = ["client"]

client = []

server = []

[[bin]]

name = "reforge_client"
path = "src/client.rs"

#[[bin]]

#name = "reforge_server"
#path = "src/server.rs"

[dependencies.pistoncore-sdl2_window]

git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.piston2d-opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.piston2d-graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.pistoncore-event]

git = "https://github.com/pistondevelopers/event"

[dependencies.pistoncore-input]

git = "https://github.com/pistondevelopers/input"

[dependencies.quack]

git = "https://github.com/pistondevelopers/quack"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[dependencies.pistoncore-window]

git = "https://github.com/pistondevelopers/window"

[dependencies.vecmath]

git = "https://github.com/pistondevelopers/vecmath"

[dependencies.freetype-rs]

git = "https://github.com/pistondevelopers/freetype-rs"


[dependencies.bincode]

git = "https://github.com/tyoverby/bincode.git"

[dependencies.time]

git = "https://github.com/rust-lang/time"

[dependencies]

rustc-serialize = "0.2.7"
